#!/usr/bin/env python3
"""The PET music engine's data, retargeted at the RIA PSG.

reference/pet/PETROBOTS12.ASM holds the original sound engine: a one-byte-per-row
pattern language, fifteen sound effects and six songs. The X16 port dropped all
of it when ZSOUND arrived -- MUSIC_ROUTINE and SET_WAVEFORM are bare RTS stubs
there -- so the patterns come from the PET sources instead.

Two things are converted:

  * The note table. The PET drives its VIA shift register, so NOTE_FREQ and
    NOTE_OCTAVE are timer values, not pitches. Note 1 is B3 and note 2 is C4, so
    note n is n-2 semitones from C4, and the RIA wants frequency in Hz times
    three.

  * The patterns, which are just bytes and copy across unchanged. The language:
    0 rests, 37 ends, 38 is note off, 39-48 set the tempo to (byte - 38), and
    1-36 play a note whose top two bits select an arpeggio mode.
"""
import argparse
import pathlib
import re
import sys

C4 = 261.6255653005986
NOTES = 36


def freq_table():
    out = [0]
    for n in range(1, NOTES + 1):
        hz = C4 * (2.0 ** ((n - 2) / 12.0))
        out.append(int(round(hz * 3.0)))       # the RIA wants Hz * 3
    return out


def grab(text, label, stop_labels):
    """The .byte lines following a label, up to the next label."""
    m = re.search(rf'^{label}:?\s*(.*)$', text, re.M)
    if not m:
        sys.exit(f"{label} not found")
    out, started = [], False
    for line in text[m.start():].splitlines():
        if started and re.match(r'^[A-Z_][A-Z0-9_]*:?\s*(?:!BYTE|$)', line) \
                and not line.startswith(label):
            if any(line.startswith(s) for s in stop_labels):
                break
        started = True
        b = re.match(r'^(?:[A-Z_][A-Z0-9_]*:?)?\s*!BYTE\s+(.*)$', line)
        if b:
            for tok in b.group(1).split(';')[0].split(','):
                tok = tok.strip()
                if tok:
                    out.append(int(tok[1:], 16) if tok.startswith('$') else int(tok))
        elif out and not re.match(r'^\s*(;.*)?$', line):
            break
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("src", type=pathlib.Path)
    ap.add_argument("dst", type=pathlib.Path)
    args = ap.parse_args()
    text = args.src.read_text(encoding="latin-1")

    names = ["SND_EXPLOSION", "SND_MEDKIT", "SND_EMP", "SND_MAGNET", "SND_SHOCK",
             "SND_MOVE_OBJ", "SND_PLASMA", "SND_PISTOL", "SND_ITEM_FOUND",
             "SND_ERROR", "SND_CYCLE_WEAPON", "SND_CYCLE_ITEM", "SND_DOOR",
             "SND_MENU_BEEP", "SND_SHORT_BEEP",
             "INTRO_MUSIC", "WIN_MUSIC", "LOSE_MUSIC",
             "IN_GAME_MUSIC1", "IN_GAME_MUSIC2", "IN_GAME_MUSIC3"]

    lines = ["; Generated by tools/convert/conv_music.py from",
             "; reference/pet/PETROBOTS12.ASM. Do not edit.",
             "",
             '        .include "petscii.inc"',
             '        .segment "RODATA"',
             ""]

    f = freq_table()
    lines += ["; Note number to RIA PSG frequency, which is hertz times three.",
              "; Note 1 is B3, note 2 is C4, so note n is n-2 semitones from C4.",
              "NOTE_FREQ_PSG:"]
    for i in range(0, len(f), 8):
        chunk = ", ".join(str(v) for v in f[i:i + 8])
        lines.append(f"        .word {chunk}")
    lines.append("")

    total = 0
    for i, name in enumerate(names):
        data = grab(text, name, names)
        if not data:
            sys.exit(f"{name}: no data")
        total += len(data)
        lines.append(f"{name}:")
        for j in range(0, len(data), 16):
            lines.append("        .byte " + ", ".join(str(b) for b in data[j:j + 16]))
    lines.append("")

    args.dst.parent.mkdir(parents=True, exist_ok=True)
    args.dst.write_text("\n".join(lines) + "\n")
    print(f"{args.dst}: {len(names)} patterns, {total} bytes of pattern data, "
          f"{NOTES} notes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
